### ISSUE TITLE
C_AVAILABLE_EVENT_MATCHING_LIST for NA 91.04

### ISSUE THREAD

**Issue by ChicknWing** [Haato3o/VG-Search#4]
Missing this opcode. Help plz.

**Comment by ChicknWing** [comment]
Also please add the new dungeon vanguards:

	"2169": "conquer corrupted skynest (cs)",
	"2170": "conquer corrupted skynest hard (csh)",
	"2171": "forbidden arena challenge (fa)",

**Comment by haato3o** [comment]
Done
`C_AVAILABLE_EVENT_MATCHING_LIST = 60213`
